From php:5.4-fpm
RUN apt update -y && \
    apt install -y php5-dev php5-mysql php5-xmlrpc libxml2 libxml2-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng12-dev libpcre3-dev libmemcached-dev && \
    pecl install memcached-2.2.0 && \
    echo "extension=memcached.so" >> /usr/local/etc/php/php.ini && \
    pecl install redis-4.3.0 && \
    echo "extension=redis.so" >> /usr/local/etc/php/php.ini && \
    docker-php-ext-install iconv mcrypt mysqli pdo pdo_mysql zip soap sockets xmlrpc && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-install gd 
RUN docker-php-ext-install mysql 
RUN docker-php-ext-install mbstring 
CMD /usr/local/sbin/php-fpm